export let products = [{
        img: "image/airpodsgen2.png",
        id: "1002",
        name: "AirPods (2rd generation)",
        price: 4900,
        stock: "2",
    },
    {
        img: "image/airpods-3rd.png",
        id: "1003",
        name: "AirPods (3rd generation)",
        price: 6700,
        stock: "6",
    },
    {
        img: "image/airpods-max.png",
        id: "1000",
        name: "AirPods Max",
        price: 19900,
        stock: "1",
    },
    {
        img: "image/Airtag.png",
        id: "2001",
        name: "Airtag",
        price: 900,
        stock: "10",
    },
    {
        img: "image/Airtagpack.png",
        id: "2005",
        name: "Airtag 4 Pack",
        price: 3390,
        stock: "5",
    },
    {
        img: "image/CaseAirTagpurple.png",
        id: "2002",
        name: "AirTag Leather Key Ring - Wisteria",
        price: 1390,
        stock: "1",
    },

    {
        img: "image/mag-safe-charger.png",
        id: "3001",
        name: "MagSafe Charger",
        price: 1490,
        stock: "5",
    },
    {
        img: "image/Apple30-pin.png",
        id: "3002",
        name: "Apple 30-pin to VGA Adapter",
        price: 1190,
        stock: "6",
    },
    {
        img: "image/Apple-Watch-Magnetic.png",
        id: "3003",
        name: "Apple Watch Magnetic Charging Dock",
        price: 2990,
        stock: "10",
    },
    {
        img: "image/MK2A3TH.png",
        id: "4000",
        name: "Magic Keyboard - Thaik",
        price: 3190,
        stock: "9",
    },
    {
        img: "image/MagicMouse.png",
        id: "4001",
        name: "Magic Mouse",
        price: 2490,
        stock: "5",
    },
    {
        img: "image/Magic-Trackpad.png",
        id: "4002",
        name: "Magic Trackpad",
        price: 4190,
        stock: "3",
    },
];